---
title: "Reference List for Critical Review"
output:
  html_document: default
  html_notebook: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(device=quartz)
#options(device="RStudioGD")
par(pin=c(2.5,2.5),las=1)
```

```{r Set WD, include=F}
setwd("/Users/raissamendonca/Documents/Kent State University/Costello Lab/GitHub/STR-FUN")

if (Sys.info()['sysname'] == 'Darwin') {
   libjvm <- paste0(system2('/usr/libexec/java_home',stdout = TRUE)[1],'/jre/lib/server/libjvm.dylib')
   message (paste0('Load libjvm.dylib from: ',libjvm))
   dyn.load(libjvm)
 }

library(VennDiagram)
library(rJava)
library(qdap)
library(tm)#
#pkgs <- c("mada", "meta", "metafor", "metasens", "mvmeta", "netmeta", "rmeta", "ellipse")
#install.packages(pkgs, repos="http://cran.rstudio.com/")

library(meta)

```

```{r Graphing code}
logaxis = function(minlog,maxlog,side){
  pow <- seq(minlog,maxlog,by=1)
  ticksat <- as.vector(sapply(pow, function(p) (1:10)*10^p))
  axis(side, 10^pow, las=1, cex.axis=0.8)
  axis(side, ticksat, labels=NA, tcl=-0.25, lwd=0, lwd.ticks=1)
}

logaxis.b = function(minlog,maxlog,side){
  pow <- seq(minlog,maxlog,by=1)
  ticksat <- as.vector(sapply(pow, function(p) (1:10)*10^p))
  axis(side, 10^pow,labels=NA, las=1)
  axis(side, ticksat, labels=NA, tcl=-0.25, lwd=0, lwd.ticks=1)
}
```


```{r Reference list dataset}
#Spreadsheet with result from first triage
refreview <- read.csv("litreview.csv",header=T,stringsAsFactors = F)
refreview <- as.vector(refreview$STR_VAR)

rr_pun <- c(removePunctuation(refreview),tolower(refreview),bracketX(refreview),stripWhitespace(refreview))
rr_sep <- unlist(strsplit(tolower(rr_pun), split=c(" ",",",";")))
rr_stem <- stemDocument(rr_sep)

new_stop <- c("impact", "respons", "effect", "chang", "assess", "activ","ecolog", stopwords("en"))
rr_clean <- removeWords(rr_stem, new_stop)

rr_freq <- as.data.frame(freq_terms(rr_clean, 10))
barplot(height=rr_freq$FREQ, names.arg = rr_freq$WORD,
        axes=T,ylim=c(0,900), xlab="Words",ylab="Count",axis.lty = 1,cex.names = 0.7, las=3, col="tomato2")

summary(rr_sep=="function")
summary(rr_sep=="structure")
summary(rr_clean=="communiti")
summary(rr_clean=="ecosystem")

#Spreadsheet cleaned up
reflist <- read.csv("litclean.csv",header=T,stringsAsFactors = F)
reflist <- as.vector(reflist$STR_VAR)

#ref_sep <- unlist(strsplit(tolower(reflist), split=c(" ","-",";")))
#ref_pun <- c(removePunctuation(reflist),tolower(ref_sep),bracketX(reflist),stripWhitespace(reflist))
#ref_stem <- stemDocument(ref_pun)
#new_stop <- c("impact", "respons", "effect", "chang", "assess", "activ","ecolog", stopwords("en"))
#ref_clean <- removeWords(ref_stem, new_stop)

ref_sep <- unlist(strsplit(tolower(reflist), split=c(" ",";")))
ref_sep <- removePunctuation(ref_sep) #66 "words" are blank for FUN and 129 for STR *summary(ref_sep=="")

ref_clean <- removeWords(ref_sep, stopwords("en"))

ref_freq <- as.data.frame(freq_terms(ref_clean, 5))
par(mfrow=c(1,2))
barplot(height=ref_freq$FREQ, names.arg = ref_freq$WORD,
        axes=T,ylim=c(0,150), xlab="Words",ylab="Count",axis.lty = 1,cex.names = 0.7, las=3, col="tomato2")

  #629 (753-129) total words for STR and 644 (710-66) for FUN

summary(ref_sep=="function")
summary(ref_sep=="structure")
summary(ref_clean=="communiti")
summary(ref_clean=="ecosystem")
```

```{r Text Mining package}
library(tm)
ref_corpus <- VCorpus(VectorSource(reflist))
inspect(ref_corpus[1:10])
meta(ref_corpus[[15]])
writeLines(as.character(ref_corpus[[12]])) # Print the content of a document

clean_corpus <- function(corpus){
  corpus <- tm_map(corpus, content_transformer(replace_abbreviation))
  corpus <- tm_map(corpus, removePunctuation)
  corpus <- tm_map(corpus, content_transformer(replace_number))
  corpus <- tm_map(corpus, removeWords, stopwords("en"))
  corpus <- tm_map(corpus, content_transformer(tolower))
  return(corpus)
}

clean_corpus(ref_corpus)
```

```{r XML datasets, include=F}
library(XML)
library(RCurl)
xmlref <- xmlTreeParse("file://Users/raissamendonca/Documents/EndNote/LitChecked.xml") # Open file with Safari and copy url
xmlref_top <- xmlRoot(xmlref)
xmlref_top <- xmlSApply(xmlref_top,
                        function(x) xmlSApply(x,xmlValue))
xmlref_df <- data.frame(t(xmlref_top),
                        row.names = NULL)

xmlref2 <- "file://Users/raissamendonca/Documents/EndNote/LitChecked.xml"
xmlref2_df <- xmlToDataFrame(xmlref2)

authors <- (xmlref_df$contributors)
abstract <- as.data.frame(xmlref2_df$abstract)
first_au <- as.data.frame(sub("([A-Za-z]+).*", "\\1", xmlref2_df$contributors))
year <- as.data.frame(sub("([0-9]+).*", "\\1", xmlref2_df$dates))
journal <- as.vector(xmlref2_df$periodical)
title <- as.vector(xmlref2_df$titles)
```

```{r Barplots freq terms}
freqterms <- read.csv("freqterms_graph.csv")
bar.col <- c("tomato2","tan1","deepskyblue3","yellowgreen","ivory3")
par(pin=c(4,2))

  #Structure graph
barplot(height=freqterms$FREQ[6:10], width = 0.5, names.arg = rep("",times=5),
        axes=T,ylim=c(0,250), xlim=c(0,6), xlab="",ylab="Word count",axis.lty = 1,cex.names = 0.8, las=2, col=bar.col)
text(x=c(0.8,1.4,2.05,2.55), y=c(-48,-50,-50,-57), labels=freqterms$WORD[7:10], srt=65, xpd=TRUE, cex = 0.8)
text(x=0.05,y=-60,label="Community", srt=65, xpd=T, cex=0.8)
text(x=0.25,y=-68,label="Composition", srt=65, xpd=T, cex=0.8)

text(x=0.35, y=215,labels="225",cex=0.7)
text(x=0.95, y=88,labels="98",cex=0.7)  
text(x=1.55, y=28,labels="38",cex=0.7)
text(x=2.15, y=26,labels="36",cex=0.7)
text(x=2.75, y=25,labels="35",cex=0.7)

  #Function graph
barplot(height=freqterms$FREQ[1:5], width = 0.5, names.arg = rep("",times=5),
        axes=T,ylim=c(0,120), xlim=c(0,6), xlab="",ylab="Word count",axis.lty = 1,cex.names = 0.8, las=2, col=bar.col)

text(x=c(0.1,0.75,1.2,1.9), y=c(-35,-29,-41,-37), labels=freqterms$WORD[1:4], srt=65, xpd=TRUE, cex = 0.8)
text(x=2.50,y=-31,label="Nutrient", srt=65, xpd=T, cex=0.8)
text(x=2.72,y=-33,label="Transformation", srt=65, xpd=T, cex=0.8)

text(x=0.35, y=100,labels="106",cex=0.7)
text(x=0.95, y=82,labels="88",cex=0.7)  
text(x=1.55, y=76,labels="82",cex=0.7)
text(x=2.15, y=55,labels="61",cex=0.7)
text(x=2.75, y=21,labels="27",cex=0.7)

```

```{r STR-FUN log-RR regressions for Cu case study}
metal <- read.csv("metal_data.csv")
  metal <- subset(metal,metal$LOG_RR>-2)
  fun <- metal[metal$PARAM_CLASS=="FUN",]
  str <- metal[metal$PARAM_CLASS=="STR",]

soil <- subset(metal,metal$UNIT=="mg/kg")
  sfun <- subset(soil,soil$PARAM_CLASS=="FUN")
  sstr <- subset(soil,soil$PARAM_CLASS=="STR")

water <- subset(metal,metal$UNIT=="ug/L")
water <- subset(water,water$CONC_X<3000)
  wfun <- subset(water,water$PARAM_CLASS=="FUN")
  wstr <- subset(water,water$PARAM_CLASS=="STR")

stress.class=as.vector(metal$PARAM_CLASS)
col.fun=grepl("FUN",stress.class)
col.str=grepl("STR",stress.class)

class.col=ifelse(col.fun==T,"deepskyblue4",
                    ifelse(col.str==T,"yellowgreen",1))

class.pch=ifelse(col.fun==T,1,
                    ifelse(col.str==T,5,13))

summary(lm(LOG_RR~log(CONC_X)+PARAM_CLASS,water))
par(pin=c(3,3))
plot(LOG_RR~CONC_X,water,pch=class.pch,col=class.col,ylim=c(-1,1),xlim=c(10,1000),log="x",xaxt="n",lwd=2,cex=1.2,xlab=expression(paste("Copper concentration (µg L"^"-1",")")),ylab="Log Response Ratio")
logaxis(1,3,1)
abline(lm(LOG_RR~log10(CONC_X),wstr),col="yellowgreen",lwd=2,lty=3)
abline(lm(LOG_RR~log10(CONC_X),wfun),col="deepskyblue4",lwd=2,lty=3)
text(28,1,labels=expression("Log RR = 0.10 - 0.03 * log[Cu]"),cex=0.6)
text(850,1,labels="p = 0.44", cex=0.6)

text(210,0.81,"Ingestion",cex=0.5)
text(210,0.87,"Respiration",cex=0.5)
text(210,0.75,"Excretion",cex=0.5)

par(xpd=T)
legend(7.5,1.3,legend="Structural measures",pch=5,col="yellowgreen",lty=3,lwd=2,bty="n",cex=0.75,pt.cex=0.8)
legend(100,1.3,legend="Functional measures",pch=1,col="deepskyblue4",lty=3,lwd=2,bty="n",cex=0.75,pt.cex=0.8)
par(xpd=F)

summary(lm(LOG_RR~log(CONC_X)+PARAM_CLASS,soil))
plot(LOG_RR~CONC_X,soil,pch=class.pch,col=class.col,xlim=c(10,10000),ylim=c(-1.5,1),log="x",xaxt="n",lwd=2,cex=1.2,xlab=expression(paste("Copper concentration (mg kg"^"-1",")")),ylab="Log Response Ratio")
logaxis(1,4,1)
abline(lm(LOG_RR~log10(CONC_X),sstr),col="yellowgreen",lwd=2,lty=3)
abline(lm(LOG_RR~log10(CONC_X),sfun),col="deepskyblue4",lwd=2,lty=3)
text(45,1,labels=expression("Log RR = 0.11 - 0.06 * log[Cu]"),cex=0.6)
text(7500,1, labels="p = 0.01", cex=0.6)

text(1800,0.74,"Nutrient transformation",cex=0.5)
```

```{r STR-FUN abs(log-RR) regressions for Cu case study}
metal <- read.csv("metal_data.csv")
  metal <- subset(metal,metal$LOG_RR>-2)
  fun <- metal[metal$PARAM_CLASS=="FUN",]
  str <- metal[metal$PARAM_CLASS=="STR",]

soil <- subset(metal,metal$UNIT=="mg/kg")
  sfun <- subset(soil,soil$PARAM_CLASS=="FUN")
  sstr <- subset(soil,soil$PARAM_CLASS=="STR")

water <- subset(metal,metal$UNIT=="ug/L")
water <- subset(water,water$CONC_X<3000)
  wfun <- subset(water,water$PARAM_CLASS=="FUN")
  wstr <- subset(water,water$PARAM_CLASS=="STR")

stress.class=as.vector(metal$PARAM_CLASS)
col.fun=grepl("FUN",stress.class)
col.str=grepl("STR",stress.class)
col.pos=metal$LOG_RR>=0
col.neg=metal$LOG_RR<0

class.col=ifelse(col.str==T,"black",
                  ifelse(col.fun==T,"darkturquoise", 1))

class.pch=ifelse(col.pos==T,3,
                    ifelse(col.neg==T,6,13))

summary.aov(lm(abs(LOG_RR)~log(CONC_X)*PARAM_CLASS,water))
par(pin=c(3,3))
plot(abs(LOG_RR)~CONC_X,water,pch=class.pch,col=class.col,ylim=c(0,2),xlim=c(10,1000),log="x",xaxt="n",lwd=2,cex=1.1,xlab=expression(paste("Copper concentration (µg L"^"-1",")")),ylab="|Log Response Ratio|")
logaxis(1,3,1)

text(840,2,labels="p = 0.46", cex=0.6)

par(xpd=T)
legend(7.5,2.3,legend="Structural measures",text.col="black",text.font=2,
       fill="black",bty="n",cex=0.75,pt.cex=0.8)
legend(100,2.3,legend="Functional measures",text.col="darkturquoise",text.font=2,
       fill="darkturquoise",bty="n",cex=0.75,pt.cex=0.8)
legend(8.1,2.41,legend="Positive log RR",col=1,pch=3,pt.lwd=2,bty="n",cex=0.75,pt.cex=0.8)
legend(106,2.41,legend="Negative log RR",col=1,pch=6,pt.lwd=2,bty="n",cex=0.75,pt.cex=0.8)
par(xpd=F)

summary.aov(lm(abs(LOG_RR)~log(CONC_X)*PARAM_CLASS,soil))
plot(abs(LOG_RR)~CONC_X,soil,pch=class.pch,col=class.col,xlim=c(1,10000),ylim=c(0,1.25),log="x",xaxt="n",lwd=2,cex=1.1,xlab=expression(paste("Copper concentration (mg kg"^"-1",")")),ylab="|Log Response Ratio|")
logaxis(0,4,1)
abline(lm(abs(LOG_RR)~log10(CONC_X),sstr),col="black",lwd=2,lty=1)
abline(lm(abs(LOG_RR)~log10(CONC_X),sfun),col="darkturquoise",lwd=2,lty=2)
text(13,1.23,labels=expression(paste("Log RR"[STR]*" = e"^"0.11 * ln[Cu] - 0.18",","," p < 0.001")),cex=0.6)
text(13,1.16,labels=expression(paste("Log RR"[FUN]*" = e"^"0.04 * ln[Cu] + 0.01",","," p < 0.001")),cex=0.6)
```

```{r STR-FUN abs(log-RR) regressions for Cu case study FUN and STR graphs}
metal <- read.csv("metal_data.csv")
  metal <- subset(metal,metal$LOG_RR>-2)
  fun <- metal[metal$PARAM_CLASS=="FUN",]
  str <- metal[metal$PARAM_CLASS=="STR",]

soil <- subset(metal,metal$UNIT=="mg/kg")
  sfun <- subset(soil,soil$PARAM_CLASS=="FUN")
  sstr <- subset(soil,soil$PARAM_CLASS=="STR")

water <- subset(metal,metal$UNIT=="ug/L")
water <- subset(water,water$CONC_X<3000)
  wfun <- subset(water,water$PARAM_CLASS=="FUN")
  wstr <- subset(water,water$PARAM_CLASS=="STR")

stress.class=as.vector(metal$PARAM_CLASS)
col.fun=grepl("FUN",stress.class)
col.str=grepl("STR",stress.class)
col.pos=metal$LOG_RR>=0
col.neg=metal$LOG_RR<0

class.col=ifelse(col.str==T,"black",
                  ifelse(col.fun==T,"darkturquoise", 15))

class.pch=ifelse(col.pos==T,3,
                    ifelse(col.neg==T,6, 13))

summary.aov(lm(abs(LOG_RR)~log(CONC_X)*PARAM_CLASS,water))
par(pin=c(1.5,3))
plot(abs(LOG_RR)~CONC_X,wstr,pch=class.pch,col="black",ylim=c(0,2),xlim=c(10,1000),log="x",xaxt="n",lwd=2,cex=1.1,xlab=expression(paste("Copper concentration (µg L"^"-1",")")),ylab="|Log Response Ratio|")
logaxis(1,3,1)
text(600,2.02,labels="p = 0.87", cex=0.5)
title("Structural measures",line=0.25,col.main="black",font.main=2,cex.main=0.9)

plot(abs(LOG_RR)~CONC_X,wfun,pch=class.pch,col="darkturquoise",ylim=c(0,2),xlim=c(10,1000),log="x",xaxt="n",lwd=2,cex=1.1,xlab="",ylab="|Log Response Ratio|")
logaxis(1,3,1)
title("Functional measures",line=0.25,col.main="darkturquoise",font.main=2,cex.main=0.9)

summary.aov(lm(abs(LOG_RR)~log(CONC_X)*PARAM_CLASS,soil))
plot(abs(LOG_RR)~CONC_X,sstr,pch=class.pch,col="black",xlim=c(1,10000),ylim=c(0,1.25),log="x",xaxt="n",lwd=2,cex=1.1,xlab=expression(paste("Copper concentration (mg kg"^"-1",")")),ylab="|Log Response Ratio|")
logaxis.b(0,4,1)
par(xpd=T)
text(x=c(1,10,100,1000,10000), y=-0.2, labels=c(1,10,100,1000,10000),srt=35,cex=0.8)
par(xpd=F)
text(3700,1.265,labels="p = 0.004", cex=0.5)
title("Structural measures",line=0.25,col.main="black",font.main=2,cex.main=0.9)
abline(lm(abs(LOG_RR)~log10(CONC_X),sstr),col="black",lwd=2,lty=2)

plot(abs(LOG_RR)~CONC_X,sfun,pch=class.pch,col="darkturquoise",xlim=c(1,10000),ylim=c(0,1.25),log="x",xaxt="n",lwd=2,cex=1.1,xlab="",ylab="|Log Response Ratio|")
logaxis.b(0,4,1)
par(xpd=T)
text(x=c(1,10,100,1000,10000), y=-0.2, labels=c(1,10,100,1000,10000),srt=35,cex=0.8)
par(xpd=F)
title("Functional measures",line=0.25,col.main="darkturquoise",font.main=2,cex.main=0.9)
abline(lm(abs(LOG_RR)~log10(CONC_X),sfun),col="darkturquoise",lwd=2,lty=2)

par(xpd=T)
legend(14000,1.32,legend="Positive log RR",col=1,pch=3,pt.lwd=2,bty="n",cex=0.75,pt.cex=0.8)
legend(14000,1.25,legend="Negative log RR",col=1,pch=6,pt.lwd=2,bty="n",cex=0.75,pt.cex=0.8)
par(xpd=F)
```

```{r STR-FUN percent change regressions for Cu case study}
metal <- read.csv("metal_data.csv")
  metal <- subset(metal,metal$LOG_RR>-2)
  metal <- subset(metal,metal$PCHANGE!="NA")
  metal <- subset(metal,metal$PCHANGE!=0)
  fun <- metal[metal$PARAM_CLASS=="FUN",]
  str <- metal[metal$PARAM_CLASS=="STR",]

soil <- subset(metal,metal$UNIT=="mg/kg")
  sfun <- subset(soil,soil$PARAM_CLASS=="FUN")
  sstr <- subset(soil,soil$PARAM_CLASS=="STR")

water <- subset(metal,metal$UNIT=="ug/L")
water <- subset(water,water$CONC_X<3000)
  wfun <- subset(water,water$PARAM_CLASS=="FUN")
  wstr <- subset(water,water$PARAM_CLASS=="STR")

stress.class=as.vector(metal$PARAM_CLASS)
col.fun=grepl("FUN",stress.class)
col.str=grepl("STR",stress.class)

class.col=ifelse(col.fun==T,"deepskyblue4",
                    ifelse(col.str==T,"yellowgreen",1))

class.pch=ifelse(col.fun==T,1,
                    ifelse(col.str==T,5,13))

summary(lm(PCHANGE~log(CONC_X),water))
par(pin=c(3,3))
plot(PCHANGE~CONC_X,water,pch=class.pch,col=class.col,ylim=c(0.01,10),xlim=c(10,1000),log="xy",xaxt="n", yaxt="n", lwd=2,cex=1.2,xlab=expression(paste("Copper concentration (µg L"^"-1",")")),ylab="Percent change (%)")
logaxis(1,3,1)
logaxis.b(-2,1,2)
axis(2,at=c(0.01,0.1,1,10),labels=c(1,10,100,1000))

text(850,10,labels="p = 0.3", cex=0.6)

par(xpd=T)
legend(7.5,23,legend="Structural measures",pch=5,col="yellowgreen",lty=3,lwd=2,bty="n",cex=0.75,pt.cex=0.8)
legend(100,23,legend="Functional measures",pch=1,col="deepskyblue4",lty=3,lwd=2,bty="n",cex=0.75,pt.cex=0.8)
par(xpd=F)

summary(lm(log(PCHANGE)~log(CONC_X),soil))
plot(PCHANGE~CONC_X,soil,pch=class.pch,col=class.col,xlim=c(10,10000),ylim=c(0.01,10),log="xy",xaxt="n", yaxt="n",lwd=2,cex=1.2,xlab=expression(paste("Copper concentration (mg kg"^"-1",")")),ylab="Percent change (%)")
logaxis(1,4,1)
logaxis.b(-2,1,2)
axis(2,at=c(0.01,0.1,1,10),labels=c(1,10,100,1000), tick = F)

abline(lm(log10(PCHANGE)~log10(CONC_X),soil),col="darkgray",lwd=2,lty=2)

text(70,10,labels=expression(paste("Percent change (%) = e"^"0.29 * ln[Cu] - 2.61")),cex=0.6)
text(7300,10, labels="p < 0.001", cex=0.6)
```
